redirect fixed
CONUN-Global/OceanDrive pull request #9
Opened 2022-05-16 02:22 UTC by otabeknos1rov

2022-05-17 02:11 UTC, IslomJonMirzakbarov requested changes
react-query/devtools removed? I think we may need it when we start work with datas, it will be much help for development

2022-05-17 08:06 UTC, JM066 commented on apps/web/src/styles/_fonts.scss
> +  font-size: 32px;
Great! You categorized this. Would it be possible to use rem instead for the font size here?

2022-05-17 12:54 UTC, otabeknos1rov commented on apps/web/src/styles/_fonts.scss
> +  font-size: 32px;
Yes it is , for clearness it is better to keep similar with style guideline from figma, isn't it?

2022-05-17 12:57 UTC, otabeknos1rov commented
> react-query/devtools removed? I think we may need it when we start work with datas, it will be much help for development

Oh , I see , yeah we can leave devtools

2022-05-18 02:48 UTC, JM066 approved these changes

2022-05-18 02:58 UTC, dbjowett approved these changes

2022-05-18 04:53 UTC, merged